### PR TITLE
Add user option to show header at point

### PR DESCRIPTION
**Pull request by yantar92**
#11

### CODE REVIEW

**Comment by alphapapa** [comment]
This option would defeat the purpose of the package. The user can already always see the heading at point. This package is like the semantic-stickyfunc-mode, but for Org.

**Comment by yantar92** [comment]
Let me explain my use case.
Consider the following org file:

```
* Bookmarks
** Learn
*** Software
***** TODO Bookmark 1
***** TODO Boorkmark 2
# ... 100+ lines
# top of the window here
***** TODO Boorkmark 123
***** Emacs
****** TODO Boorkmark 124
****** TODO Bookmark 125 >-(point)-<
```

The higher levels of hierarchy (Bookmarks/Learn/Software/Emacs) are not visible for the indicated point position. I would like to use the package to see the full org path (using `(setq org-sticky-header-full-path 'full)`). 

The current implementation shows the org path for the top of the window only: "Bookmarks/Learn/Software/Bookmark 123". I want to see "Bookmarks/Learn/Software/Emacs/Bookmark 125".

**Comment by alphapapa** [comment]
I understand what you're wanting, but that's not what this package is intended to do.  It's intended to show the hierarchy that is off the screen, so that the user knows what heading the top of the screen is under.  It's the Org analog of `semantic-stickyfunc-mode`.

In your case, you can infer the path you want to see by deriving it from the one that's visible and the other headings on the screen.

I would prefer not to add the setting you proposed unless there are a number of other users who also need it.  Of course, you can easily use `advice-add` to customize the function in your own configuration.

This feature can also be provided by `eldoc-mode`.  In Org buffers, it shows the current heading path when point is on a heading.  You can easily modify it to show the current heading path regardless of where point is by overriding `org-eldoc-documentation-function` like so:
```el
(defun ap/org-eldoc-documentation-function ()
  "Return breadcrumbs when on a headline, args for src block header-line,
  calls other documentation functions depending on lang when inside src body."
  (or
   (org-eldoc-get-breadcrumb)
   (org-eldoc-get-src-header)
   (let ((lang (org-eldoc-get-src-lang)))
     (cond ((or
             (string= lang "emacs-lisp")
             (string= lang "elisp")) (if (fboundp 'elisp-eldoc-documentation-function)
             (elisp-eldoc-documentation-function)
             (let (eldoc-documentation-function)
               (eldoc-print-current-symbol-info))))
           ((or
             (string= lang "c") ;; http://github.com/nflath/c-eldoc
             (string= lang "C")) (when (require 'c-eldoc nil t)
             (c-eldoc-print-current-symbol-info)))
           ;; https://github.com/zenozeng/css-eldoc
           ((string= lang "css") (when (require 'css-eldoc nil t)
                                   (css-eldoc-function)))
           ;; https://github.com/zenozeng/php-eldoc
           ((string= lang "php") (when (require 'php-eldoc nil t)
                                   (php-eldoc-function)))
           ((or
             (string= lang "go")
             (string= lang "golang")) (when (require 'go-eldoc nil t)
             (go-eldoc--documentation-function)))
           (t (let ((doc-fun (org-eldoc-get-mode-local-documentation-function lang)))
                (when (functionp doc-fun) (funcall doc-fun))))))
   ;; Added to always show outline path, even when point is not on a heading:
   (org-format-outline-path (org-get-outline-path t)
                            (frame-width) "" org-eldoc-breadcrumb-separator)))

(advice-add #'org-eldoc-documentation-function :override #'ap/org-eldoc-documentation-function)
```

**Comment by yantar92** [comment]
Thank you. You suggestion will also work for me.

**Pull request closed without merging**
